source 'https://github.com/CocoaPods/Specs.git'
target 'PlannerApp' do
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire', '~> 4.7'
    pod 'GooglePlacePicker'
end
